name: Deploy to live

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive # Ensures submodules are initialized

      - name: Debug Workflow
        run: |
          echo "Current Branch: $GITHUB_REF"
          echo "Actor: $GITHUB_ACTOR"
          echo "Secrets Branch: ${{ secrets.BRANCH }}"

      - name: Initialize and Update Submodules
        run: git submodule update --init --recursive || echo "No submodules found"

      - run: git fetch --prune --unshallow
      - run: git config --global user.email "${{ github.actor }}@noreply.github.com"
      - run: git config --global user.name "${{ github.actor }}"

      - name: Check for Changes Before Committing
        run: |
          git status
          git add .
          if ! git diff --cached --exit-code; then
            git commit -m "Build"
          else
            echo "No changes to commit. Skipping commit step."
          fi

      - name: GitHub Action for Main
        uses: uraayush/github-action-wpengine-git-deploy@master
        env:
          WPENGINE_ENVIRONMENT_NAME: ${{ secrets.WPENGINE_ENVIRONMENT_NAME }}
          WPENGINE_SSH_KEY_PRIVATE: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
          WPENGINE_SSH_KEY_PUBLIC: ${{ secrets.WPENGINE_SSH_KEY_PUBLIC }}
          LOCAL_BRANCH: ${{ secrets.BRANCH }}
